Fix KeyError due to identation problem
Using the forward_proxy with an intermittent link to the server the following error was being generated:

  File "/usr/local/lib/python2.7/dist-packages/coapthon/layers/blocklayer.py", line 183, in receive_response
    del self._block2_sent[key_token]
KeyError: -8448607242250672825